### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Neerajms25** [riazXrazor/realtime-face-recognition#1]
bro when i try to run server it shows like this
>  npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Neer\Appta\Roamig\npm-cache\_logs\2020-08-12T12_58_58_386Z-debug.log

**Comment by Neerajms25** [comment]
And also when i try to run index.js file it returns error as follows

-  node index.js
D:\realtime-face-recognition-master\socket.js:3
if (!cv.xmodules.face) {
                 ^

TypeError: Cannot read property 'face' of undefined
    at Object.<anonymous> (D:\realtime-face-recognition-master\socket.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\realtime-face-recognition-master\index.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

**Comment by Neerajms25** [comment]
can u please tell me .Thank u broo

**Comment by Neerajms25** [comment]
bro when i try to run server it shows like this

npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Neer\Appta\Roamig\npm-cache_logs\2020-08-12T12_58_58_386Z-debug.log

**Comment by riazXrazor** [comment]
you have open cv installed properly right ?

**Comment by Neerajms25** [comment]
properly in the sense i used npm to install opencv4nodejs.
I have to install opencv also ?.

**Comment by Neerajms25** [comment]
I also checked for face module and it is present in the opencv4nodejs module als brooo

**Comment by riazXrazor** [comment]
Yup its jst a wrapper for opencv


On Aug 13, 2020 at 9:49 AM, Neerajms25 <notifications@github.com> wrote:

properly in the sense i used npm to install opencv4nodejs.
I have to install opencv also ?.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/riazXrazor/realtime-face-recognition/issues/1#issuecomment-673245669>,
or unsubscribe
